### PR TITLE
Add basic RTC API

### PR DESCRIPTION
**Pull request by hannobraun**
This pull request adds a very basic RTC API. It can be used to read and set the time, but no alarms or other interrupts are supported yet. There are also a few commits adding general debug stuff to the `time` module, as that was useful to me while I developed this.

I'm marking this PR as a draft, as it's based on #25. Otherwise, this is ready to review.

cc @lthiery

### CODE REVIEW

**Comment by hannobraun** [comment]
Build fails for STM32L0x1 due to warnings. Will fix shortly.

**Comment by hannobraun** [comment]
There was also another problem that was masked by the first: The RTC example only works on STM32L0x2.

Everything's fixed now. Pull request has been rebased. I've rolled the fixes into the existing commits.

This is ready for review now.

**Comment by arkorobotics** [comment]
You rock! Thanks again for all your recent PRs!

**Comment by hannobraun** [comment]
> You rock! Thanks again for all your recent PRs!

Thank you :-)
And thank you again for all the reviewing/merging!

**Pull request merged**
