### PR TITLE
Added preliminary support for STM32L0x3 parts

### PR DESCRIPTION
**Pull request by therealprof**
Signed-off-by: Daniel Egger <daniel@eggers-club.de>

### CODE REVIEW

**Comment by therealprof** [comment]
@arkorobotics ping? The CI breakage comes from the NVIC changes which @Disasm addressed in his PR #30, but we can certainly separate those out if you' like to see a green CI before merging.

**Comment by arkorobotics** [comment]
Thanks so much for adding L0x3 support! 

For this PR, I'd prefer we keep the CI checks clean. We can either move forward with a separate PR minus NVIC changes or we can have @hannobraun to review/approve PR #30 first. If Hanno is busy or unable to review it soon, I'll address the PR on Wednesday when I have a moment to review it in detail.

**Comment by Disasm** [comment]
I'm OK with splitting #30 in two, so that we have this PR before version bump.

**Comment by arkorobotics** [comment]
Seems this PR is breaking after merging #30. I haven't done a deep dive but it looks like it's complaining about unused variables. If it's alright with you, I'd like to ask to have this resolved before merging. Once this is resolved, I'll merge and bump the version.

**Comment by therealprof** [comment]
That seems to be fallout from the NVIC change, i.e. #30 not being sufficient in that the `nvic` parameter passed into the `exti` functions is now unused.

**Comment by therealprof** [comment]
Uhm, that was a weird artifact of criss-cross-merging. You really should try not to do that. That was somewhat annoying to fix, it completely threw git off the rails.

**Comment by arkorobotics** [comment]
Yikes... Sorry, I didn't mean for that to happen. I'll merge this now.

**Comment by arkorobotics** [comment]
@therealprof To be honest, I have no clue if I did the right thing here... but everything has been merged and rolled up into 0.3.0. Please let me know if you see any glaring issues.

**Comment by therealprof** [comment]
Looks all good now.

**Pull request merged**
