### PR TITLE
Improve USB module

### PR DESCRIPTION
**Pull request by hannobraun**
This improves the `usb` module, bringing it more in line with other modules and making the API less error-prone.

### CODE REVIEW

**Comment by arkorobotics** [comment]
Great! Given all the recent additions, I think it's time to release the current repo (after merging this) as v0.5.0. Thoughts? Do we want to close out all open issues before doing so?

**Comment by hannobraun** [comment]
> Great! Given all the recent additions, I think it's time to release the current repo (after merging this) as v0.5.0. Thoughts? Do we want to close out all open issues before doing so?

Sorry for the late reply! A new release sounds good to me.

Regarding the open issues, I definitely plan to close #42 before the year is over, but I wouldn't block the release on that. I currently have no plans to work on #52.

I plan to add a Flash API very soon (pull request incoming this week, if nothing goes wrong, but who knows). Don't know, if you want to wait for that.

**Comment by Disasm** [comment]
Is HSI48 absolutely required for USB to work on L0?

**Comment by hannobraun** [comment]
> Is HSI48 absolutely required for USB to work on L0?

I think there are other clocks that can be used in its place, although I don't recall the details right now. HSI48 is the only one currently supported in the HAL API.

**Comment by arkorobotics** [comment]
@hannobraun No worries. Let's wait for the Flash API. That sounds like a great addition before the next rev (no pressure 😛).

**Pull request merged**
