### PR TITLE
Add set_frequency method on PWM channels

### PR DESCRIPTION
**Pull request by azerupi**
Following discussion in #172  this adds a method to PWM channels to change the underlying timer's frequency. This allows to dynamically change the PWM frequency when we have already associated a channel with a pin. Otherwise this required unsafe to work around a partial move error because the channel was moved out of the timer struct.

In the implementation I changed `clock_frequency` on the `Instance` to not take `&self`. This allows it to be used in the channels. But this is not required, we could access the RCC register directly to avoid making a breaking change?

Compared to the timer's implementation we don't stop and start the timer before changing the frequency. I tested it on my project and it seems to work flawlessly. I'm not sure why that was required in the timer's implementation? If it needs to be added, is there a way to reuse the timer's implementation without copy-pasting?

Let me know if anything can be improved! :slightly_smiling_face:

### CODE REVIEW

**Comment by azerupi** [comment]
The clippy failure is the same as what I got in #173, it has been fixed there.

**Review by hannobraun — APPROVED** [review]
Thank you, @azerupi!

**Comment by azerupi** [comment]
Great, thanks!

Just to make sure, you did see this part?
>In the implementation I changed clock_frequency on the Instance to not take &self.

Because I think that is a breaking change since `Instance` is public. :slightly_smiling_face:

**Comment by dbrgn** [comment]
Breaking changes are fine, we have breaking changes all the time. However, maybe you could send a PR that updates the CHANGELOG?

**Comment by hannobraun** [comment]
I did see that, but thanks for pointing it out again. I could have been a bit less terse :slightly_smiling_face: 

While it is strictly speaking a breaking change, I don't think there's much reason for end users to touch `Instance` except in trait bounds. Its methods are more of an internal API, although Rust won't let us express that. So I think this change has pretty low impact, and given that, I believe that using `unsafe` to conjure up an `Rcc` is not worth it in this case.

Also, what @dbrgn said, we break things all the time :smile: In a perfect world, we'd take more steps to avoid/alleviate that, but we have to work with the resources we've got (on the maintainer and contributor side).

**Pull request merged**
